@php
    $title = 'Privacy Policy';
    $description = "The security of your personal information is very important to Citrus Labs Limited and we
                    appreciate you for trusting us in safekeeping your personal information.";
@endphp
@include('home_partials.home_header')
<style>
    h1,
    h2,
    h3,
    h4,
    h5,
    h6,
    p,
    li {
        margin-bottom: 0.5rem;
        margin-top: 0.5rem;
    }

    h1,
    h2,
    h3,
    h4,
    h5,
    h6 {
        margin-bottom: 0.25rem;
        margin-top: 0.25rem;
    }

    .terms li {
        list-style-type: disc;
    }

    .terms .list-style-none {
        list-style-type: none;
    }


    ol.list-style-lower-alpha li {
        list-style-type: lower-alpha !important;
    }

    .terms ul,
    .terms ol {
        padding-left: 2rem
    }
</style>


<section class="terms">
    <div class="container py-5">
        <div class="row pt-5 mt-5">
            <div class="col-md-8 m-auto">
                <h1 class="fw-bold text-center">Privacy Policy</h1>
                <p>The security of your personal information is very important to Citrus Labs Limited and we
                    appreciate you for trusting us in safekeeping your personal information. We will work hard
                    to protect the security and privacy of any personal information you provide to us and will
                    only use such information as we have described herein. This page informs you of our policies
                    regarding the collection, use and disclosure of personal data when you use our Service and
                    the choices you have.</p>
                <p>
                    Citrus Labs Limited ("us", "we", or "our") operates https://scribble.ke/ a bulk short message
                    service (SMS) platform and its related services (hereinafter referred to as the "Service"). This
                    page informs you of our policies regarding the collection, use and disclosure of personal data
                    when you use our Service and the choices you have associated with that data.
                </p>
                <p>
                    We use your data to provide and improve the Service. By using the Service, you agree and
                    consent to the collection and use of information in accordance with this policy. Unless
                    otherwise defined in this Privacy Policy, the terms used in this Privacy Policy have the same
                    meanings as in our Terms of service, accessible from http://scribble.ke/terms-and-conditions
                </p>
                <p>
                    This privacy policy applies to personal information we hold about individuals. We will only
                    use your personal information in accordance with the Constitution of Kenya, the Data
                    Protection Act, 2019, other laws relating to data protection and privacy in Kenya and this
                    privacy policy. We wish to notify you of your rights provided for under Section 26 of the Data
                    Protection Act, 2019 and you are free to exercise the said rights at any point. Please read the
                    following Privacy Policy to understand how Citrus Labs Limited uses the Personal Data we
                    may collect from you.
                </p>
                <p> By providing your personal data to us, you are voluntarily consenting to this Privacy Policy
                    and the collection, use, access, transfer, storage and processing of your personal information
                    as described in this Policy.
                </p>
                <h2>Definitions</h2>
                <ul class="">
                    <li class="h4 fw-bold">Service</li>
                    <li class="list-style-none">
                        Service is the https://scribble.ke/ operated by Citrus Labs Limited.
                    </li>
                    <li class="h4 fw-bold">
                        Personal Data
                    </li>
                    <li class="list-style-none">
                        Personal Data means data about a living individual who can be identified from those
                        data (or from those and other information either in our possession or likely to come
                        into our possession).
                    </li>

                    <li class="h4 fw-bold">Usage Data
                    </li>
                    <li class="list-style-none">
                        Usage Data is data collected automatically either generated by the use of the Service
                        or from the Service infrastructure itself (for example, the duration of a page visit).
                    </li>
                    <li class="h4 fw-bold">
                        Cookies
                    </li>
                    <li class="list-style-none">
                        Cookies are small files stored on your device (computer or mobile device).Data Controller
                        Data Controller means the natural or legal person who (either alone or jointly or in
                        common with other persons) determines the purposes for which and the manner in
                        which any personal information are or are to be processed. For the purpose of this
                        Privacy Policy, we are a Data Controller of your Personal Data.
                    </li>
                    <li class="h4 fw-bold">
                        Data Processors (or Service Providers)
                    </li>
                    <li class="list-style-none">

                        Data Processor (or Service Provider) means any natural or legal person who processes
                        the data on behalf of the Data Controller. We may use the services of various Service
                        Providers in order to process your data more effectively.
                    </li>
                    <li class="h4 fw-bold">Data Subject (or User)</li>
                    <li class="list-style-none">
                        Data Subject is any living individual who is using our Service and is the subject of

                        Personal Data.
                    </li>
                </ul>
                <h2> Information Collection and Use</h2>
                <ul>
                    <li>We collect several different types of information for various purposes to provide and
                        improve our Service to you.
                    </li>
                </ul>
                <h2> Types of Data Collected</h2>
                <ul class="">
                    <li class="h4 fw-bold">Personal Data</li>
                    <li class="list-style-none">
                        While using our Service, we may ask you to provide us with certain personally
                        identifiable information that can be used to contact or identify you ("Personal
                        Data").
                        Personally identifiable information may include, but is not limited to:
                    </li>
                </ul>
                <ol class=" list-style-lower-alpha">
                    <li>Email address</li>
                    <li>First name and last name</li>
                    <li>Phone number</li>
                    <li>Address, State, Province, ZIP/Postal code, City</li>
                    <li>Cookies and Usage Data</li>
                </ol>
                <ul class="">
                    <li class="list-style-none">
                        We may use your Personal Data to contact you with
                        newsletters, marketing or promotional materials and other information that may be of
                        interest to you. You
                        may opt out of receiving any, or all of these communications from us by following
                        the unsubscribe link or the instructions provided in any email we send.
                    </li>
                    <li class="h4 fw-bold">
                        Usage Data
                    </li>
                    <li class="list-style-none">
                        We may also collect information on how the Service is accessed and used ("Usage
                        Data"). This Usage Data may include information such as your computer's Internet
                        Protocol address (e.g. IP address), browser type, browser version, the pages of
                        our Service that you visit, the time and date of your visit, the time spent on those
                        pages, unique device identifiers and other diagnostic data.Location Data
                        We may use and store information about your location if you give us permission
                        to do so ("Location Data"). We use this data to provide features of our Service, to
                        improve and customise the Service. You can enable or disable location services when you
                        use our Service at any time by way of device settings.
                    </li>
                    <li class="h4 fw-bold"> Tracking & Cookies Data</li>
                    <li class="list-style-none"> We use cookies and similar tracking technologies to track the
                        activity on our
                        Service
                        and we hold certain information.
                    </li>
                    <li class="list-style-none"> Cookies are files with a small amount of data which may include an
                        anonymous
                        unique identifier. Cookies are sent to your browser from a website and stored on
                        your
                        device. Other tracking technologies are also used such as beacons, tags and
                        scripts
                        to
                        collect and track information and to improve and analyse our Service.
                    </li>
                    <li class="list-style-none">
                        You can instruct your browser to refuse all cookies or to indicate when a cookie
                        is
                        being sent. However, if you do not accept cookies, you may not be able to use
                        some
                        portions of our Service. Examples of Cookies we use:
                    </li>
                </ul>
                <ol class=" list-style-lower-alpha">
                    <li><b>Session Cookies</b>. We use Session Cookies to operate our Service.</li>
                    <li><b> Preference Cookies</b>. We use Preference Cookies to remember your preferences
                        and
                        various settings.</li>
                    <li><b>Security Cookies</b>. We use Security Cookies for security purposes.</li>
                </ol>
                <h2>
                    Use of Data
                </h2>
                <p>We use the collected data for various purposes:</p>
                <ol class=" list-style-lower-alpha">
                    <li>To provide and maintain our Service.</li>
                    <li> To notify you about changes to our Service.</li>
                    <li>To allow you to participate in interactive features of our Service when you
                        choose to
                        do so.</li>
                    <li>To provide customer support.</li>
                    <li>To gather analysis or valuable information so that we can improve our
                        Service.</li>
                    <li>To monitor the usage of our Service.</li>
                    <li> To detect, prevent and address technical issues.</li>
                    <li>To provide you with news, special offers and general information about other
                        goods,
                        services and events which we offer that are similar to those that you already
                        purchased
                        or enquired about unless you have opted not to receive such information, for
                        data
                        trading purposes to other firms and political figures, however you shall have
                        the
                        right
                        to withdraw consent at any time.
                    </li>
                </ol>
                <h2>Legal Basis for Processing Personal Data under
                    the
                    General
                    Data
                    Protection Regulation
                    (GDPR)</h2>
                <p>
                    If you are from the European Economic Area (EEA), Citrus Labs Limited's legal
                    basis
                    for
                    collecting and using the personal information described in this Privacy Policy
                    depends on
                    the
                    Personal Data we collect and the specific context in which we collect it. We may
                    process
                    your
                    Personal Data because:</p>
                <ol class=" list-style-lower-alpha">
                    <li>We need to perform a contract with you.</li>
                    <li>You have given us permission to do so.</li>
                    <li>The processing is in our legitimate interests and it is not overridden by
                        your
                        rights.</li>
                    <li>For payment processing purposes.</li>
                    <li>To comply with the law.</li>
                </ol>
                <h2> Retention of Data</h2>
                <ul class="">
                    <li>We will retain your Personal Data only for as long as is necessary for the
                        purposes set
                        out in this Privacy Policy. We will retain and use your Personal Data to the
                        extent
                        necessary to comply with our legal obligations (for example, if we are required
                        to
                        retain your data to comply with applicable laws), resolve disputes and enforce
                        our
                        legal agreements and policies.</li>
                    <li>We will also retain Usage Data for internal analysis purposes. Usage Data is
                        generally
                        retained for a shorter period of time, except when this data is used to
                        strengthen
                        the
                        security or to improve the functionality of our Service, or it is legally
                        obligated
                        to
                        retain
                        this data for longer periods.</li>
                </ul>
                <h2>Transfer of Data</h2>
                <ul class="">
                    <li>Your information, including Personal Data, may be transferred to — and
                        maintained
                        on — computers located outside of your State, province, country or other
                        governmental jurisdiction where the data protection laws may differ from those
                        of
                        your jurisdiction.
                    </li>
                    <li>you are located outside Kenya and choose to provide information to us,
                        please
                        note
                        that Citrus Labs Limited transfers the data, including Personal Data, to Kenya
                        and
                        will
                        process it there.</li>
                    <li>
                        consent to this Privacy Policy followed by your submission of such
                        information
                        represents your agreement to that transfer.
                    </li>
                    <li>
                        We will take all the steps reasonably necessary to ensure that your data is
                        treated
                        securely and in accordance with this Privacy Policy and no transfer of such
                        Personal
                        Data will take place to an organisation or a country unless there are adequate
                        controls
                        in place including the security of such data and other personal
                        information.
                    </li>
                </ul>
                <h2> Disclosure of
                    Data</h2>
                <ul class=>
                    <li class="h4"> Business Transaction</li>
                    <li class="list-style-none">
                        If Citrus Labs Limited is involved in a merger, acquisition or asset sale, your
                        Personal
                        Data may be transferred. We will provide notice before such Personal Data is
                        transferred and becomes subject to a different Privacy Policy.
                    </li>
                    <li class="h4">Legal requirements</li>
                    <li class="list-style-none">
                        We may disclose your Personal Data in good faith and in belief that such action
                        is
                        necessary:
                        <ol class=" list-style-lower-alpha">
                            <li>To comply with a legal obligation.</li>
                            <li>To protect and defend the rights or property of Citrus Labs Limited.</li>
                            <li>To prevent or investigate possible wrongdoing in connection with the Service.</li>
                            <li>To protect the personal safety of users of the Service or the public.</li>
                            <li>To protect against legal liability.</li>
                        </ol>
                    </li>
                </ul>
                <h2>Security of Data</h2>
                <ul>
                    <li>
                        The security of your data is important to us but remember that no method of
                        transmission over the Internet or method of electronic storage is 100% secure.
                        While
                        Citrus Labs Limited strives to use commercially acceptable means to protect such
                        Personal Data, we cannot guarantee its absolute security.
                    </li>
                </ul>
                <h2>
                    Your Data Protection Rights under the General Data Protection Regulation (GDPR)
                </h2>
                <p> If you are a resident of the European Economic Area (EEA), you have certain data
                    protection
                    rights. We aim to take reasonable steps to allow you to correct, amend, delete
                    or
                    limit the
                    use
                    of such Personal Data.
                </p>
                <p>
                    If you wish to be informed about what Personal Data we hold about you and if you
                    want to
                    be removed from our systems, please contact us.
                </p>
                <p> In certain circumstances, you will have the following data protection rights:</p>
                <ol class=" list-style-lower-alpha">
                    <li>The right to access, update or delete the information we may have on you.
                        Whenever
                        made possible, you can access, update or request deletion of such Personal Data
                        directly within your account settings section. If you are unable to perform
                        these
                        actions
                        personally, please contact us for assistance.</li>
                    <li>The right of rectification. You will have the right to have such information
                        rectified if
                        that information is inaccurate or incomplete.</li>
                    <li>The right to object. You have the right to object to our processing of such
                        Personal
                        Data.</li>
                    <li>The right of restriction. You have the right to request that we restrict the
                        processing
                        of
                        such personal information.</li>
                    <li>The right to data portability. You have the right
                        to be
                        provided
                        with a
                        copy of the
                        information we have on you in a structured, machine-readable and commonly used
                        format.</li>
                    <li>The right to withdraw consent. You also have the right to withdraw such
                        consent
                        at
                        any time where we relied on such consent to process your personal information.</li>
                </ol>
                <ul class="">
                    <li>Please note that we may ask you to verify your identity before responding to
                        such
                        requests. You have the right to complain to a Data Protection Authority about
                        such
                        collection and use of such Personal Data. For more information, please contact
                        the
                        local
                        data protection authority in the European Economic Area (EEA).
                    </li>
                </ul>
                <h2>Service Providers</h2>
                <ul class="">
                    <li>
                        We may employ third party companies and individuals to facilitate our Service
                        ("Service Providers"), provide the Service on our behalf, perform
                        Service-related
                        services or assist us in analysing how the Service is used.
                    </li>
                    <li>
                        These third parties will have access to your Personal Data only to perform
                        these
                        tasks
                        on our behalf and are obligated not to disclose or use it for any other purpose.</li>
                </ul>
                <h2>Analytics</h2>
                <p>We may use third-party Service Providers to monitor and analyse the use of our
                    Service.
                <ul class="">
                    <li class="fw-bold">
                        Google Analytics
                    </li>
                    <li class="list-style-none">
                        Google Analytics is a web analytics service offered by Google that tracks and
                        reports
                        website traffic. Google uses the data collected to track and monitor the use of
                        the
                        Service. This data is shared with other Google services. Google may use the
                        collected
                        data to contextualise and personalise the ads of its own advertising network.
                    </li>
                    <li class="list-style-none">
                        You can opt-out of having made such activity on the Service available to Google
                        Analytics by installing the Google Analytics opt-out browser add-on. The add-on
                        prevents the Google Analytics JavaScript (ga.js, analytics.js and dc.js) from
                        sharing
                        information with Google Analytics about visits activity.
                    <li class="list-style-none">
                        For more information on the privacy practices of Google, please visit the Google
                        Privacy & Terms web page: https://policies.google.com/privacy?hl=en
                    </li>
                    </li>
                </ul>

                <h2>Payments</h2>
                <p> We may provide paid products and/or services within the Service. In that case,
                    we use third-party
                    services for payment processing (e.g. payment processors).
                </p>
                <p>
                    We will not store or collect your payment card details. That information is
                    provided
                    directly
                    to our third-party payment processors whose use of such personal information is
                    governed
                    by their Privacy Policy. These payment processors adhere to the standards set by
                    PCI-DSS as
                    managed by the PCI Security Standards Council, which is a joint effort of brands
                    like Visa,
                    MasterCard, American Express and Discover. PCI-DSS requirements help ensure the
                    secure
                    handling of payment information.</p>
                <p>payment processors we work with are:
                </p>
                <ul class="">
                    <li class="fw-bold">MPESA</li>
                    <li class="list-style-none"> Their Privacy Policy can be viewed at
                        https://domains.safaricom.co.ke/privacy.php</li>
                </ul>
                <h2> Links to other sites</h2>
                <ul class="">
                    <li class="list-style-none">
                        Our Service may contain links to other sites that are not
                        operated by us. If
                        you
                        click a
                        third party link, you will be directed to that third party's site. We strongly
                        advise you
                        to review the Privacy Policy of every site you visit.</li>
                    <li class="list-style-none">
                        We have no control over and assume no responsibility for the content, privacy
                        policies
                        or practices of any third party sites or services.
                    </li>
                </ul>
                <h2> Children's Privacy</h2>
                <ul class="">
                    <li class="list-style-none">
                        We do not address anyone under the age of 18 ("Children").
                    </li>
                    <li class="list-style-none">
                        We do not knowingly collect personally identifiable information from anyone
                        under
                        the age of 18. If you are a parent or guardian and is aware that a child has
                        provided us
                        with Personal Data, please contact us. If we become aware that such Personal
                        Data
                        has
                        been collected from children without verification of parental consent, we will
                        take
                        steps to remove that information from our servers.
                    </li>
                </ul>

                <h2>Changes to this Privacy Policy</h2>
                <ul class="">
                    <li class="list-style-none">
                        We may update our Privacy Policy from time to time. We will notify you of any
                        changes by posting the new Privacy Policy on this page.
                    </li>
                    <li class="list-style-none">
                        We will let you know via email and/or a prominent notice on our Service, prior
                        to
                        the
                        change becoming effective and update the "effective date" at the top of this
                        Privacy
                        Policy.
                    </li>
                    <li class="list-style-none"> You are advised to review this Privacy Policy
                        periodically for any changes.
                        Changes
                        to this Privacy Policy are effective when they are posted on this page.
                    </li>
                </ul>
                <h2> Our Contacts</h2>
                <p> If you have any questions about this Privacy Policy, please contact Citrus Labs
                    Limited:</p>
                <ul class="">
                    <li class="list-style-none">
                        By email: Legal@citrus.co.ke
                    </li>
                    <li class="list-style-none">
                    <li class="list-style-none">By visiting this page on our website:
                        http://scribble.ke/terms-and-conditions
                    </li>
                    <li class="list-style-none">By phone number: +254 20 213 1200</li>
                    </li>
                </ul>
            </div>
        </div>
    </div>
</section>

<!--footer -->
@include('home_partials/home_footer')

</body>

</html>
